### PR TITLE
update dependencies for security audit

### PR DESCRIPTION
**Pull request by swarajpure**
These dependencies are updated by `npm audit fix`

### CODE REVIEW

**Comment by swarajpure** [comment]
This PR updates the at least the first 2 dependencies to safe versions:
image

**Review by rohan09-raj — COMMENTED** [review]
@swarajpure How we will be updating other dependencies ??

**Comment by swarajpure** [comment]
> @swarajpure How we will be updating other dependencies ??

There is no patch for them till now. We'll have to remove the packages which use those dependencies and replace them with some packages. That'll require some efforts.

This PR will take at least make some steps in reducing the vulnerabilities in our repo.

**Comment by rohan09-raj** [comment]
> > @swarajpure How we will be updating other dependencies ??
> 
> There is no patch for them till now. We'll have to remove the packages which use those dependencies and replace them with some packages. That'll require some efforts.
> 
> This PR will take at least make some steps in reducing the vulnerabilities in our repo.

Ok got it, it's a manual work

**Comment by rohan09-raj** [comment]
Closing the PR as we are no longer using `package-lock` instead we are using `yarn.lock`

**Pull request closed without merging**
