### PR TITLE
Https Development workflow using local-ssl-proxy

### PR DESCRIPTION
**Pull request by sanyogita14**

### CODE REVIEW

**Review by swarajpure — CHANGES_REQUESTED** [review]
Great job! Thanks for the change! 🙌🏻

We already have a note in README about CORS. With your setup, users are half done for solving CORS, they still need need to change their /etc/hosts file (step 1 of that doc), can we mention this in our README also?

**Comment by sanyogita14** [comment]
> Great job! Thanks for the change! 🙌🏻
> 
> We already have a note in README about CORS. With your setup, users are half done for solving CORS, they still need need to change their /etc/hosts file (step 1 of that doc), can we mention this in our README also?

Yeah sure. What do I need to add to the README file?

**Comment by swarajpure** [comment]
> > Great job! Thanks for the change! 🙌🏻
> > We already have a note in README about CORS. With your setup, users are half done for solving CORS, they still need need to change their /etc/hosts file (step 1 of that doc), can we mention this in our README also?
> 
> Yeah sure. What do I need to add to the README file?

Note: For solving CORS errors, please make sure to follow step 1 from this document (link here). This project has taken care of step 2 in itself.

**Comment by sanyogita14** [comment]
> > > Great job! Thanks for the change! 🙌🏻
> > > We already have a note in README about CORS. With your setup, users are half done for solving CORS, they still need need to change their /etc/hosts file (step 1 of that doc), can we mention this in our README also?
> > 
> > 
> > Yeah sure. What do I need to add to the README file?
> 
> Note: For solving CORS errors, please make sure to follow step 1 from this document (link here). This project has taken care of step 2 in itself.

Ok. But I have to make those changes on my local computer right - to resolve `dev.realdevsquad.com` to `localhost`? So what changes do I have to make to the code?

**Comment by swarajpure** [comment]
> > > > Great job! Thanks for the change! 🙌🏻
> > > > We already have a note in README about CORS. With your setup, users are half done for solving CORS, they still need need to change their /etc/hosts file (step 1 of that doc), can we mention this in our README also?
> > > 
> > > 
> > > Yeah sure. What do I need to add to the README file?
> > 
> > 
> > Note: For solving CORS errors, please make sure to follow step 1 from this document (link here). This project has taken care of step 2 in itself.
> 
> Ok. But I have to make those changes on my local computer right - to resolve `dev.realdevsquad.com` to `localhost`? So what changes do I have to make to the code?

That's what the doc is about
My previous comment was about what to write in the README
Doc link: https://github.com/Real-Dev-Squad/website-code-docs/tree/main/docs/dev/https-dev-url-cors

**Review by swaraj-rajpure — APPROVED** [review]
LGTM! Thanks for this one! :zap:

**Review by swarajpure — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
