### PR TITLE
Fixed timestamp issue in review statement

### PR DESCRIPTION
**Pull request by ardourApeX**
### Purpose
Reviewed log should show the timestamp when the request was reviewed and not when it was created
### Issue Ticket
- https://github.com/Real-Dev-Squad/website-my/issues/486

### Proposal Doc
https://docs.google.com/document/d/1sf-BAs7C6wmfjRVS-82X492hcb_7jAfIM-7pWtizuXE/edit

### Frontend Changes
- [x] Yes
- [ ] No

### Is Under Feature Flag
- [x] Yes
- [ ] No

### Database changes: 
- [ ] Yes
- [x] No

### Breaking changes (If your feature is breaking/missing something please mention pending tickets): 
- [ ] Yes
- [x] No

### Deployment notes:
NA

### Tested in local
- [x] Yes
- [ ] No

### List of PRs going in this Sync
- https://github.com/Real-Dev-Squad/website-backend/pull/1635

### QA Instructions, Screenshots, Recordings

Run `yarn test:ember` and there you can see test case running.
Screenshot 2023-10-29 at 11 45 23

### Working Proof
This extension request was made 1 week ago and was approved few hours ago

Before:
Screenshot 2023-10-29 at 11 39 57

After: 
Screenshot 2023-10-29 at 11 40 17

### CODE REVIEW

**Comment by shubhamsigdar1** [comment]
Link issue ticket please.

**Review by shubhamsigdar1 — COMMENTED** [review]
What is meaning of reviewed here??

**Comment by ardourApeX** [comment]
This feature is related to the audit log. A user who has submitted an extension request should be able to see who has reviewed it. To achieve this, we are using 'reviewedBy.' It should also display when it was reviewed. Previously, I was using 'timestamp,' which actually indicates when the extension request was created. However, I have now replaced it with 'reviewedAt,' which denotes when the request was reviewed.

Screenshot 2023-10-29 at 7 47 34 PM

**Review by shubhamsigdar1 — COMMENTED** [review]
Where is test written for this changes??

**Comment by ardourApeX** [comment]
> Where is test written for this changes??

It's already been written. You check it here in the screenshot
Screenshot 2023-10-29 at 8 08 46 PM

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]

**Pull request merged**
