### PR TITLE
hide navbar for signup page

### PR DESCRIPTION
**Pull request by sushanth97**

### CODE REVIEW

**Comment by sushanth97** [comment]
This PR contains changes for this [issue](https://github.com/Real-Dev-Squad/website-my/issues/144). Please review this.

**Comment by swarajpure** [comment]
Excellent job in there @sushanth97!

Tested this locally and seems to be working fine

There have been new changes in the develop branch which have fixed the failing checks in github CI. Can you please do the following and push your branch?
- checkout to develop locally: `git checkout develop`
- take pull from RDS::develop: `git pull origin develop` (please check if origin points to RDS (Real Dev Squad) than your own fork, by doing `git remote -v`)
- checkout to this branch again: `git checkout patch_hide_navbar_insignup_page`
- rebase this branch on top of updated local develop branch: `git rebase develop`
- If you face any conflicts, please resolve them. Mostly you should not, you might face one for package-lock, you can just do an `npm i` to fix it
- now you can push your branch, you'll face some error that the local branch and remote branch don't match, which makes sense you've made changes to the branch history by rebasing. You should force push now and changes should be reflected in this PR :)

Apologies for the delay in response @sushanth97

**Comment by sushanth97** [comment]
Thanks @swarajpure. I tried the above mentioned steps but getting permission error when tried to push the changes.

Screen Shot 2021-12-16 at 6 38 27 PM

Please check and let me know if I have missed anything

**Comment by swarajpure** [comment]
Hey @sushanth97, apologies for the delay in response
I don't check github notifications that often

We (Real Dev Squad) communicate over Discord server. Would you like to be a part of the same?
Here's the joining link: https://discord.gg/xrJJFbDY

Your query would have been resolved much faster if asked on Discord.

Anyway, coming to your question, when you're pushing, you should push branch of **your fork**, you can't push to Real Dev Squad branches unless you're org member.

This should solve your issue: `git push origin patch_hide_navbar_insignup_page` (where origin points to your fork, can check by `git remote -v`)
That was a mistake from my side. Apologies for that.

Thank you so much for your pull request 🚀

**Comment by sushanth97** [comment]
@swarajpure Thanks for the steps. I have pushed the changes successfully. Please review.

**Review by swarajpure — APPROVED** [review]
Awesome! Thanks for this one!

Congratulations on your first pull request in Real Dev Squad! 🔥

**Pull request merged**
